// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 
    appId: '1:431136500893:web:2688570b7e1db53cd6b874',
    messagingSenderId: '431136500893',
    projectId: 'phoneauth-5d330',
    authDomain: 'phoneauth-5d330.firebaseapp.com',
    storageBucket: 'phoneauth-5d330.appspot.com',
    measurementId: 'G-XV1DJMQTL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 
    appId: '1:431136500893:android:5487a122879639c4d6b874',
    messagingSenderId: '431136500893',
    projectId: 'phoneauth-5d330',
    storageBucket: 'phoneauth-5d330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:,
    appId: '1:431136500893:ios:e6b0a1b7160437ead6b874',
    messagingSenderId: '431136500893',
    projectId: 'phoneauth-5d330',
    storageBucket: 'phoneauth-5d330.appspot.com',
    iosBundleId: 'com.example.phoneauthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6cO89QwFhOBOZjRiM1pc07upf1HCNjF0',
    appId: '1:431136500893:ios:e6b0a1b7160437ead6b874',
    messagingSenderId: '431136500893',
    projectId: 'phoneauth-5d330',
    storageBucket: 'phoneauth-5d330.appspot.com',
    iosBundleId: 'com.example.phoneauthFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_8s1fNNjwFZZ42QP29OuxpRY2hTpzRFY',
    appId: '1:431136500893:web:81fc2cc45bbbf4fbd6b874',
    messagingSenderId: '431136500893',
    projectId: 'phoneauth-5d330',
    authDomain: 'phoneauth-5d330.firebaseapp.com',
    storageBucket: 'phoneauth-5d330.appspot.com',
    measurementId: 'G-CVFKJSWZ09',
  );
}
